### PR TITLE
Navbar on small screens, hover over content

### PR DESCRIPTION
**Pull request by ZPPD**
# Fixes

Nav menu on small screens hovers over the content and is more concise. 
I have kept the height of the empty div with a class of topnav-placeholder.

## Related Issues

- https://github.com/ufosc/club-website/issues/35

### CODE REVIEW

**Comment by ZPPD** [comment]
Not sure if you need the div for anything. Do you want me to deleted it along with the styles, or just to comment out the height?

**Comment by mirdaki** [comment]
I can't seem to find a reason for it, so if you could remove it and the styling (and do a double check to make sure it doesn't effect anything else haha), I'd appreciate it!

**Comment by ZPPD** [comment]
I just pushed the changes to the same branch. Let me know how that is.

**Comment by mirdaki** [comment]
This is great! The only changes I've made were to remove the topnav-placeholder from all of the other pages and some extra whitespace I found. Thank you so much for your help! We've been wanting to update this for a while.

**Comment by ZPPD** [comment]
Forgot about the other pages lol. No problem, I am happy to help.

**Pull request merged**
